version: "3.3"
services:
  db:
    image: mariadb:10.4
    restart: always
    volumes:
      - ./data:/data
    working_dir: /data
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: librarypass
      MYSQL_DATABASE: library
  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080
  web:
    build: .
    volumes:
      - ./library:/app
    working_dir: /app
    command: ./wait-for-it.sh db:3306 -t 60 -s -- sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
